config/routes.rb
match 'auth/failure', controller: :easyauth, action: :easyauth_failure, via: %i[get post]
match 'auth/easyauth/login', controller: :easyauth, action: :easyauth_login, via: [:get], as: :easyauth_signin

app/controllers/easyauth_controller.rb
class EasyauthController < AccountController
  include RedmineEasyauthHelper

  def easyauth_failure
    flash['error'] = "#{l('easyauth.error.authentication_failed')}: #{params[:message]}"
    redirect_to signin_path
  end

  def easyauth_login
    unless settings['enabled']
      flash['error'] = l('easyauth.error.disabled')
      redirect_to signin_path
      return
    end

    login, name, claims = easyauth_claims
    if login.blank? or name.blank?
      logger.info 'easyauth unavailable'
      flash['error'] = l('easyauth.error.authentication_unavailable')
      redirect_to signin_path
      return
    end

    oid1 = claims.fetch('groups', [])
    oid2 = claims.fetch('oid', [])
    oid3 = claims.fetch('http://schemas.microsoft.com/identity/claims/objectidentifier', [])
    claim_groups = (oid1 + oid2 + oid3).map(&:strip).map(&:downcase).reject(&:blank?).uniq
    logger.info "easyauth claim groups: #{claim_groups.inspect}"

    allowed_groups = settings['allowed_principal_list'].to_s.split(',').map(&:strip).map(&:downcase).reject(&:blank?).uniq
    logger.info "easyauth allowed groups: #{allowed_groups.inspect}"

    if allowed_groups.any? && (allowed_groups & claim_groups).empty?
      logger.info 'easyauth disallowed'
      flash['error'] = l('easyauth.error.authentication_disallowed')
      redirect_to signin_path
      return
    end

    user = User.joins(:email_addresses)
               .where('email_addresses.address' => name, 'email_addresses.is_default' => true)
               .first_or_initialize

    if user.new_record?
      unless settings['auto_registration']
        logger.info 'easyauth auto registration disabled'
        flash['error'] = l('easyauth.error.auto_registration_disabled')
        redirect_to signin_path
        return
      end
      user.login = (claims.fetch('preferred_username', []) + [name]).first
      user.mail = name
      user.firstname = (claims.fetch('name', []) + [name]).first
      user.lastname =  easyauth_mail_org_translate(name) || EASYAUTH_MAIL_ORG_RULE_DEFAULT
      user.admin = false
      user.register
      user.activate
      user.last_login_on = Time.now
      if user.save
        self.logged_user = user
        flash[:notice] = l(:notice_account_activated)
        redirect_to my_account_path
        return
      end
      logger.info 'easyauth auto registration failed'
      flash['error'] = l('easyauth.error.auto_registration_failed')
      redirect_to signin_path
      return
    end

    if user.active?
      successful_authentication(user)
      return
    end

    account_pending(user)
  end

  def settings
    @settings ||= Setting.plugin_redmine_easyauth
  end
end

app/views/easyauth/_signin.html.erb
<%= stylesheet_link_tag 'easyauth', plugin: 'redmine_easyauth' %>

<% login, mail, claims = easyauth_claims %>
<% if Setting.plugin_redmine_easyauth['enabled'] %>
  <%= content_tag :div, id: 'easyauth-form' do %>
    <%= form_tag easyauth_signin_path, method: :get do %>
      <%= label_tag nil do %>
        <%= l('easyauth.field.login') %>
        <%= link_to "/.auth/login/aad?prompt=select_account&post_login_redirect_uri=#{request.path}", class: 'account_switch' do %>
          <%= l('easyauth.label.switch_account') %>
        <% end %>
      <% end %>
      <%= text_field_tag nil, login, readonly: true %>
      <%= label_tag nil do %>
        <%= l('easyauth.field.mail') %>
      <% end %>
      <%= text_field_tag nil, mail, readonly: true %>
      <%= submit_tag l('easyauth.label.login') %>
    <% end %>
  <% end %>
<% end %>

<% if !Setting.plugin_redmine_easyauth['announcement'].blank? %>
  <%= content_tag :div, id: 'easyauth-announcement' do %>
    <%=raw Redmine::WikiFormatting.to_html(Setting.text_formatting, Setting.plugin_redmine_easyauth['announcement']) %>
  <% end %>
<% end %>

app/views/settings/_easyauth_settings.html.erb
<p>
  <%= label_tag nil, l('easyauth.setting.enabled') %>
  <%= check_box_tag 'settings[enabled]', true, @settings['enabled'] %>
</p>
<p>
  <%= label_tag nil, l('easyauth.setting.auto_registration') %>
  <%= check_box_tag 'settings[auto_registration]', true, @settings['auto_registration'] %>
</p>
<p>
  <%= label_tag nil, l('easyauth.setting.allowed_principal_list') %>
  <%= text_field_tag 'settings[allowed_principal_list]', @settings['allowed_principal_list'], :size => 80 %>
</p>
<p>
  <%= label_tag nil, l('easyauth.setting.announcement') %>
  <%= text_area_tag "settings[announcement]", @settings['announcement'], :rows => 5 %>
</p>
<p>
  <%= label_tag nil, l('easyauth.setting.mail_org_rules') %>
  <%= text_area_tag "settings[mail_org_rules]", @settings['mail_org_rules'], :rows => 5, :placeholder => "# Comment\n@foo\\.example\\.com$ [FOO]\n@bar\\.example\\.org$ [BAR]" %>
  <em class="info"><%= l('easyauth.help.mail_org_rules') %></em>
</p>